// Writes src/elements.data.ts from the npm package `periodic-table-data` (MIT; its numbers are
// PubChem's periodic table), issue #250. The element facts a periodic-table question is checked
// against come from this data, never from a model — and never typed in by hand either.
//
// Only what the figure and its keys need is kept, as four space-separated strings in order of
// atomic number: symbol, atomic mass, Pauling electronegativity ("-" where the source has none)
// and a one-letter class (m metal, s metalloid, n nonmetal). Group and period are not data: they
// follow from the atomic number (`periodic.ts`).
//
//   node packages/shared-math/scripts/elements.mjs          write the file
//   node packages/shared-math/scripts/elements.mjs --check  fail if the file is out of date
//
// `src/__tests__/periodic.test.ts` runs the same comparison, so a changed package version shows.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'src', 'elements.data.ts');
const require = createRequire(import.meta.url);
const pkg = require('periodic-table-data/package.json');

/** The source's `groupBlock` as the three classes a school table draws. */
const CLASS = {
  'Alkali metal': 'm',
  'Alkaline earth metal': 'm',
  'Transition metal': 'm',
  'Post-transition metal': 'm',
  Lanthanide: 'm',
  Actinide: 'm',
  Metalloid: 's',
  Nonmetal: 'n',
  Halogen: 'n',
  'Noble gas': 'n',
};

export function render(rows) {
  const sorted = [...rows].sort((a, b) => a.atomicNumber - b.atomicNumber);
  sorted.forEach((e, i) => {
    if (e.atomicNumber !== i + 1) throw new Error(`gap in the table at ${i + 1}`);
    if (!(e.groupBlock in CLASS)) throw new Error(`unknown class ${e.groupBlock} (${e.symbol})`);
    if (!(Number(e.atomicMass) > 0)) throw new Error(`no mass for ${e.symbol}`);
  });
  const en = (v) => (typeof v === 'number' && v > 0 ? String(v) : '-');
  // Laid out as prettier lays out a string too long for one line, so the check stays byte-exact.
  const line = (name, doc, values) =>
    `/** ${doc} */\nexport const ${name} =\n  '${values.join(' ')}';\n`;
  // The package's licence travels with its data, as the MIT licence asks.
  const licence = readFileSync(require.resolve('periodic-table-data/LICENSE'), 'utf8')
    .trim()
    .split('\n')
    .filter((l) => l.trim() !== '')
    .map((l) => `// ${l.trim()}`);
  return [
    `// GENERATED by packages/shared-math/scripts/elements.mjs from ${pkg.name} ${pkg.version}`,
    `// (${pkg.license}; PubChem's periodic table). Do not edit: run the script. Issue #250.`,
    '//',
    ...licence,
    '',
    line(
      'SYMBOLS',
      'Element symbols in order of atomic number.',
      sorted.map((e) => e.symbol),
    ),
    line(
      'MASSES',
      'Atomic mass in u, same order.',
      sorted.map((e) => String(Number(e.atomicMass))),
    ),
    line(
      'NEGATIVITY',
      'Pauling electronegativity, same order; "-" for none.',
      sorted.map((e) => en(e.electronegativity)),
    ),
    line(
      'CLASSES',
      'm metal, s metalloid, n nonmetal, same order.',
      sorted.map((e) => CLASS[e.groupBlock]),
    ),
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const rows = require('periodic-table-data/periodicTableData.json');
  const text = render(rows);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== text) {
      console.error(
        'src/elements.data.ts is out of date: run node packages/shared-math/scripts/elements.mjs',
      );
      process.exit(1);
    }
  } else {
    writeFileSync(target, text);
  }
}
