// SvgStimulus — render server-supplied SVG diagrams safely.
// Doc 07 §3.6 + Doc 06 §post-processing-svg-safety. Items can carry an SVG
// stimulus generated by the LLM (geometry items, labelled diagrams, etc).
// We never trust the markup verbatim: lib/svg/sanitize.ts strips it down to
// a presentational whitelist before this component hands it to
// react-native-svg's SvgXml.
//
// If sanitization rejects everything the component falls back to a calm
// text placeholder so the question card still composes correctly.

import { useMemo } from 'react';
import { Text, View } from 'react-native';
import { SvgXml } from 'react-native-svg';

import { sanitizeSvg } from '../../lib/svg/sanitize.js';
import { LB } from '../../lib/theme/colors.js';

type Props = {
  /** Raw SVG markup as emitted by the LLM / template renderer. */
  svg: string;
  width?: number;
  height?: number;
  /** Fallback label shown when sanitization rejects the input. The caller
   *  owns user-visible text so this component stays i18n-neutral. */
  fallbackLabel: string;
};

export function SvgStimulus({ svg, width = 280, height = 200, fallbackLabel }: Props) {
  const sanitized = useMemo(() => sanitizeSvg(svg), [svg]);
  if (!sanitized.ok) {
    return (
      <View
        accessibilityRole="image"
        accessibilityLabel={fallbackLabel}
        style={{
          width,
          height,
          backgroundColor: LB.bg,
          borderRadius: 14,
          borderColor: LB.hairline,
          borderWidth: 1,
          alignItems: 'center',
          justifyContent: 'center',
          padding: 16,
        }}
      >
        <Text
          style={{
            fontSize: 13,
            color: LB.ink2,
            textAlign: 'center',
            lineHeight: 18,
          }}
        >
          {fallbackLabel}
        </Text>
      </View>
    );
  }
  return (
    <View accessibilityRole="image" accessibilityLabel={fallbackLabel}>
      <SvgXml xml={sanitized.svg} width={width} height={height} />
    </View>
  );
}
