// @learnbuddy/shared-maps — maps from Natural Earth (public domain) for the app and the server
// (issue #251). docs/architecture.md §Practice ("Maps"). The data is generated by
// scripts/build-maps.mjs; everything here is plain functions over it.

export * from './features.js';
export * from './graticule.js';
export * from './hit.js';
export * from './names.js';
export type * from './types.js';
