-- The questions of one material (docs/architecture.md §Material, §Practice).
--
-- "Frage passt nicht": the learner takes a bad question out of a running
-- session. It is closed as 'skipped' (no FSRS review) and archived for the
-- future; flagged_at tells it apart from a skipped or revealed question, so it
-- counts neither as answered nor as shaky.
alter table session_items add column flagged_at timestamptz;

-- The order questions were stored in (the order on the sheet): items written in
-- one transaction share created_at, so the list needs its own sequence.
alter table items add column seq bigint generated by default as identity;
