-- 0024 — Probe assessments: D2 of the Phase D fake-understanding catcher.
-- Source: docs/LEARNER-EXPERIENCE-PLAN.md §Phase D.
--
-- Phase D1 added confidence_probe + wrong_example_probe selector moves.
-- Those moves cause the tutor to ASK a probe question. This table
-- captures the LEARNER'S RESPONSE classification, generated by the
-- tutor LLM on the turn immediately after a probe.
--
--   probe_move    — which probe triggered the response (so we can
--                   tune them independently).
--   quality       — substantive | rephrased | gave_up.
--                   'substantive' = real reasoning that addresses WHY.
--                   'rephrased' = just restated the answer in different
--                                 words — the pattern-matcher signal.
--                   'gave_up' = "idk", shrug, empty.
--   response_excerpt — first ~280 chars of the learner's response, for
--                      later analysis. Truncated server-side.
--
-- pattern_match_signal isn't a column — it's an AGGREGATE over this
-- table:
--   count('rephrased') / count(*) over last 30d for this learner.
-- The selector can read it on demand (slow path, cache it later).
--
-- L1: this table is purely diagnostic. The learner never sees their
-- own quality classification. The system uses it to choose better
-- moves (more probes when pattern_match_signal is high, fewer when
-- it's already known the kid reasons substantively).

create table probe_assessments (
  id uuid primary key default gen_random_uuid(),
  learner_id uuid not null references learners(id) on delete cascade,
  session_id uuid not null references sessions(id) on delete cascade,
  item_id uuid references items(id) on delete set null,
  turn_index int not null,
  probe_move text not null check (
    probe_move in ('confidence_probe', 'wrong_example_probe', 'self_explanation_prompt')
  ),
  quality text not null check (quality in ('substantive', 'rephrased', 'gave_up')),
  response_excerpt text,
  created_at timestamptz not null default now()
);

create index probe_assessments_learner_idx
  on probe_assessments (learner_id, created_at desc);

create index probe_assessments_session_idx
  on probe_assessments (session_id, turn_index);

alter table probe_assessments enable row level security;
-- Service-role only — never surfaced to the learner.
