// GENERATED by packages/shared-math/scripts/elements.mjs from periodic-table-data 1.1.1
// (MIT; PubChem's periodic table). Do not edit: run the script. Issue #250.
//
// MIT License
// Copyright (c) 2023 Jianfeng Song
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

/** Element symbols in order of atomic number. */
export const SYMBOLS =
  'H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og';

/** Atomic mass in u, same order. */
export const MASSES =
  '1.008 4.0026 7 9.012183 10.81 12.011 14.007 15.999 18.99840316 20.18 22.9897693 24.305 26.981538 28.085 30.973762 32.07 35.45 39.9 39.0983 40.08 44.95591 47.867 50.9415 51.996 54.93804 55.84 58.93319 58.693 63.55 65.4 69.723 72.63 74.92159 78.97 79.9 83.8 85.468 87.62 88.90584 91.22 92.90637 95.95 96.90636 101.1 102.9055 106.42 107.868 112.41 114.818 118.71 121.76 127.6 126.9045 131.29 132.905452 137.33 138.9055 140.116 140.90766 144.24 144.91276 150.4 151.964 157.2 158.92535 162.5 164.93033 167.26 168.93422 173.05 174.9668 178.49 180.9479 183.84 186.207 190.2 192.22 195.08 196.96657 200.59 204.383 207 208.9804 208.98243 209.98715 222.01758 223.01973 226.02541 227.02775 232.038 231.03588 238.0289 237.048172 244.0642 243.06138 247.07035 247.07031 251.07959 252.083 257.09511 258.09843 259.101 266.12 267.122 268.126 269.128 270.133 269.1336 277.154 282.166 282.169 286.179 286.182 290.192 290.196 293.205 294.211 295.216';

/** Pauling electronegativity, same order; "-" for none. */
export const NEGATIVITY =
  '2.2 - 0.98 1.57 2.04 2.55 3.04 3.44 3.98 - 0.93 1.31 1.61 1.9 2.19 2.58 3.16 - 0.82 1 1.36 1.54 1.63 1.66 1.55 1.83 1.88 1.91 1.9 1.65 1.81 2.01 2.18 2.55 2.96 3 0.82 0.95 1.22 1.33 1.6 2.16 1.9 2.2 2.28 2.2 1.93 1.69 1.78 1.96 2.05 2.1 2.66 2.6 0.79 0.89 1.1 1.12 1.13 1.14 - 1.17 - 1.2 - 1.22 1.23 1.24 1.25 - 1.27 1.3 1.5 2.36 1.9 2.2 2.2 2.28 2.54 2 1.62 2.33 2.02 2 2.2 - 0.7 0.9 1.1 1.3 1.5 1.38 1.36 1.28 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 - - - - - - - - - - - - - - -';

/** m metal, s metalloid, n nonmetal, same order. */
export const CLASSES =
  'n n m m s n n n n n m m m s n n n n m m m m m m m m m m m m m s s n n n m m m m m m m m m m m m m m s s n n m m m m m m m m m m m m m m m m m m m m m m m m m m m m m s n n m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m n n';
