// Maps (issue #251): a stumme Karte of Germany's 16 Länder, of the countries of Europe or of the
// continents, as atlases print them — and the one rule for what a region on it is called.
// docs/architecture.md §Practice, Maps.
//
// The regions are DATA, never a model's word: their names in the five languages and their shapes
// come from Natural Earth (public domain), generated by `scripts/maps.mjs` into two files —
// `maps.data.ts`, the names, which the server checks every map question against, and
// `mapShapes.data.ts`, the shapes, which only the app needs and loads when a map is on the screen
// (`useMapShapes`). The model only NAMES a region; code resolves the name (`mapRegion`), and a
// name no region has costs the question (`apps/api/src/modules/practice/mapCheck.ts`).
//
// A map is answered by tapping a region — the tap mechanism of every figure (`tap.ts`, issue
// #248): its one axis is the regions, a tap's text is the region's German name. Which region a
// finger means is `regionAt` (`regions.ts`, shared with the parts of a labelled picture): the
// region under it, or — for one smaller than a finger (Berlin, Bremen) — the one whose label it is
// near, or else the nearest region.
//
// Dependency-free on purpose: the app imports it by path, like `tap.ts`.

import { MAP_HEIGHTS, MAP_NAMES } from './maps.data.js';
import { regionName, regionNamed, type RegionName, type RegionSet } from './regions.js';

export const MAP_VIEWS = ['de', 'europe', 'world'] as const;
export type MapView = (typeof MAP_VIEWS)[number];
export type MapNames = Readonly<Record<MapView, readonly RegionName[]>>;
/** The shapes of a view: its regions in the order of `MAP_NAMES` (`regions.ts`), and more. */
export type MapViewShape = RegionSet & {
  /** false: a region is many countries (a continent) — drawn as one outline, no inner border. */
  borders: boolean;
  /** Land around the frame that is no region (Turkey on a map of Europe): drawn, never tapped. */
  context: readonly string[];
};
export type MapShapes = Readonly<Record<MapView, MapViewShape>>;

/** The shape of `MapFigure` (packages/shared-types/src/contracts/map.ts). */
export type MapFig = { type: 'map'; v: MapView; hl: readonly string[] };

export function isMap(f: { type: string }): f is MapFig {
  return f.type === 'map';
}

/** The regions of a view, in drawing order. */
export function mapRegions(v: MapView): readonly RegionName[] {
  return MAP_NAMES[v];
}

/** How high a view stands in a frame `REGION_FRAME` wide. */
export function mapHeight(v: MapView): number {
  return MAP_HEIGHTS[v];
}

/**
 * The index of the region `name` names on view `v` — "Bayern", "Bavaria", "BY" (`regionNamed`) —
 * or null when no region of the view has that name.
 */
export function mapRegion(v: MapView, name: string): number | null {
  return regionNamed(MAP_NAMES[v], name);
}

/** The region's name in `lang` (German where the app's language is none of the five). */
export function mapRegionName(v: MapView, index: number, lang: string): string {
  return regionName(MAP_NAMES[v], index, lang);
}

/**
 * The first reason a map cannot be drawn as written, or null: a marked region the view does not
 * have, or one marked twice.
 */
export function mapProblem(f: MapFig): string | null {
  const marked = f.hl.map((n) => mapRegion(f.v, n));
  const unknown = f.hl.find((_, i) => marked[i] === null);
  if (unknown !== undefined) return `no region "${unknown}" on the map ${f.v}`;
  if (new Set(marked).size !== marked.length) return 'a region is marked twice';
  return null;
}

/** The map with every marked region written as its id ("Bavaria" → "BY"): what is stored. */
export function mapCanonical<F extends MapFig>(f: F): F {
  return { ...f, hl: f.hl.map((n) => MAP_NAMES[f.v][mapRegion(f.v, n) ?? -1]?.id ?? n) };
}

/** The indices of the marked regions (a name no region has marks nothing). */
export function mapMarked(f: MapFig): number[] {
  return f.hl.map((n) => mapRegion(f.v, n)).filter((i): i is number => i !== null);
}
