// The licences of what the app ships (issue #493): every package in the iOS and Android bundle,
// with its version, its licence and the licence text it asks to travel with it. `licences.json`
// is generated by tools/guards/licences.mjs, never written by hand; a list that no longer matches
// the bundle is red in `bundle:check` (pre-commit and CI). Each text is stored once and shared by
// the packages that carry it word for word.
//
// Loaded on demand (`lazyModule`, components/settings/LicencesSheet.tsx): nobody opening the app
// to practise downloads a hundred licence texts.

import data from './licences.json';

type Licence = { name: string; version: string; licence: string; text: string };

/**
 * A licence file is wrapped for an 80-column terminal; on a phone those breaks cut every line in
 * two. The words stay as they are; a line break goes where it means something: between
 * paragraphs, before a list item ("1.", "*", "(a)") and before a heading's underline.
 */
export function reflow(text: string): string {
  return text
    .replace(/([^\n])\n(?!\n|[ \t]*(?:(?:[-*•]|\d+[.)]|\([a-z0-9]+\))[ \t]|[=-]{3,}))/g, '$1 ')
    .replace(/[ \t]{2,}/g, ' ');
}

export const LICENCES: readonly Licence[] = data.packages.map(({ text, ...entry }) => ({
  ...entry,
  text: reflow(data.texts[text] ?? ''),
}));
